import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./styles/globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Student Data Table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className}max-w-[1145px] bg-[#F9F9FA] py-[68px] px-[68px] mx-auto`}
      >
        <div>
          <h1 className="text-[#343434] pb-[54px] font-black text-[40px]">
            Student Data Table
          </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
